name: logmaster
version: 0.1.0
description: >
  A logger intended to catch exceptions or simply report activity,
  then post it to a server or store locally fo further inspection.
  
  The idea is that catching errors and forming error messages is separate from
  actually reporting them. By loading report-adapters on demand, we can use this library
  both in the backend and in the frontend.

author: Roman Snitko <roman.snitko@gmail.com>
homepage: https://github.com/snitko/dart-logmaster

dependencies:
dev_dependencies:
  test: '>=0.12.0'
dependency_overrides:
